export const IMAGES = {
    LOAD_REQUEST: 'LOAD_IMAGES_REQUEST',
    LOAD_SUCCESS: 'LOAD_IMAGES_SUCCESS',
    LOAD_FAILURE: 'LOAD_IMAGES_FAILURE',
};

export const IMAGE = {
    CREATE_REQUEST: 'CREATE_IMAGE_REQUEST',
    CREATE_SUCCESS: 'CREATE_IMAGE_SUCCESS',
    CREATE_FAILURE: 'CREATE_IMAGE_FAILURE',

    DELETE_REQUEST: 'DELETE_IMAGE_REQUEST',
    DELETE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
    DELETE_FAILURE: 'DELETE_IMAGE_FAILURE',

    UPDATE_REQUEST: 'UPDATE_IMAGE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_IMAGE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_IMAGE_FAILURE',
}
